= Xataface Ajax Upload Module

Copyright (C) 2012  Steve Hannah

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


== Synopsis

The ajax_upload module adds a file upload widget to Xataface that uses AJAX.


== Features

. Adds the ajax_upload widget type for use in a Xataface application.
. Will work with any container field (i.e. file upload fields where the files are stored on the file system).
. AJAX uploading of files.
. Will work inside grid widget (so you can now have unlimited file uploads to a form).
. LightBox preview of images.
. Progress bar to track upload progress.
. Delete or replace files in field.


== Requirements:

- Xataface 2.0 or higher
- PHP 5+ with GD image extension enabled.

Recommended that PHP has fileinfo extension enabled also.


== Installation:

1. Copy the ajax_upload directory into the modules directory of either your application or Xataface.
2. Add the following to the [_modules] section of your conf.ini file:

	modules_ajax_upload=modules/ajax_upload/ajax_upload.php
	

== Usage

This module provides the ajax_upload widget type that can be used in place of the file
widget.  E.g. If you have a field that you used to use for file uploads with configuration
like:

[source,ini]
----
[myfield]
	Type=container
----
	
	
You can change it to use the ajax_upload widget by adding:

[source,ini]
----
widget:type=ajax_upload
----
	
to the fields.ini configuration.  E.g.

[source,ini]
----
[myfield]
	Type=container
	widget:type=ajax_upload
----
		
		
== Limitations 

- Does not work on BLOB fields yet.  Only container fields.


== Support

http://xataface.com/forum